# Generated by Django 4.1.7 on 2025-03-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explearning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explearning',
            name='id',
        ),
        migrations.AddField(
            model_name='explearning',
            name='poster_ID',
            field=models.IntegerField(default=1741847312, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
