# Generated by Django 4.1.7 on 2025-03-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explearning", "0003_total_scores_exp_learning"),
    ]

    operations = [
        migrations.RenameField(
            model_name="explearning",
            old_name="poster_ID",
            new_name="poster_id",
        ),
        migrations.RenameField(
            model_name="explearning",
            old_name="research_score",
            new_name="reflection_score",
        ),
        migrations.RenameField(
            model_name="explearning",
            old_name="Student",
            new_name="student",
        ),
        migrations.RenameField(
            model_name="total_scores_exp_learning",
            old_name="avg_research_score",
            new_name="avg_reflection_score",
        ),
    ]
