# Generated by Django 4.1.7 on 2025-03-26 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_scores_round_1_feedback"),
        ("threemt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Total_Scores_ThreeMT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("judged_count", models.IntegerField(default=0)),
                ("avg_comprehension_content", models.FloatField(default=0)),
                ("avg_engagement", models.FloatField(default=0)),
                ("avg_communication", models.FloatField(default=0)),
                ("avg_overall_impression", models.FloatField(default=0)),
                ("total_score", models.FloatField(default=0)),
                (
                    "poster_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.students"
                    ),
                ),
            ],
            options={
                "verbose_name": "Total Scores Three Minute Thesis",
                "verbose_name_plural": "Total Scores Three Minute Thesis",
                "db_table": "total_scores_three_mt",
            },
        ),
    ]
