# Generated by Django 4.1.7 on 2025-03-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("threemt", "0002_total_scores_threemt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="threemt",
            old_name="poster_ID",
            new_name="poster_id",
        ),
        migrations.RenameField(
            model_name="threemt",
            old_name="Student",
            new_name="student",
        ),
    ]
