# Generated by Django 4.1.7 on 2024-03-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_scores_round_1_graduate',
            name='judged_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='total_scores_round_1_undergraduate',
            name='judged_count',
            field=models.IntegerField(default=0),
        ),
    ]
