# Generated by Django 4.1.7 on 2024-03-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_total_scores_round_1_graduate_judged_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores_round_1',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
